"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as descriptor
from google.protobuf import message as message
from google.protobuf.internal import enum_type_wrapper as enum_type_wrapper
import builtins as builtins
import sys
import typing as typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: descriptor.FileDescriptor

@typing.final

HealthCheckRequest: HealthCheckRequest

class HealthCheckRequest(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SERVICE_FIELD_NUMBER: builtins.int
    service: builtins.str
    def __init__(
        self,
        *,
        service: builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["_service", b"_service", "service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["_service", b"_service", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__service: _TypeAlias = typing.Literal["service"]  # noqa: Y015
    _WhichOneofArgType__service: _TypeAlias = typing.Literal["_service", b"_service"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__service) -> _WhichOneofReturnType__service | None: ...

@typing.final

HealthCheckResponse: HealthCheckResponse

class HealthCheckResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    class _ServingStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ServingStatusEnumTypeWrapper(enum_type_wrapper.EnumTypeWrapper[HealthCheckResponse._ServingStatus.ValueType], builtins.type):
        DESCRIPTOR: descriptor.EnumDescriptor
        UNKNOWN: HealthCheckResponse._ServingStatus.ValueType  # 0
        SERVING: HealthCheckResponse._ServingStatus.ValueType  # 1
        NOT_SERVING: HealthCheckResponse._ServingStatus.ValueType  # 2
        SERVICE_UNKNOWN: HealthCheckResponse._ServingStatus.ValueType  # 3

    class ServingStatus(_ServingStatus, metaclass=_ServingStatusEnumTypeWrapper): ...
    UNKNOWN: HealthCheckResponse.ServingStatus.ValueType  # 0
    SERVING: HealthCheckResponse.ServingStatus.ValueType  # 1
    NOT_SERVING: HealthCheckResponse.ServingStatus.ValueType  # 2
    SERVICE_UNKNOWN: HealthCheckResponse.ServingStatus.ValueType  # 3

    STATUS_FIELD_NUMBER: builtins.int
    status: HealthCheckResponse.ServingStatus.ValueType
    def __init__(
        self,
        *,
        status: HealthCheckResponse.ServingStatus.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["_status", b"_status", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["_status", b"_status", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__status: _TypeAlias = typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = typing.Literal["_status", b"_status"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...
